<?php

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            ['role','Quản lý vai trò','el_roles',null],
            ['role-create','Thêm vai trò',null,'role'],
            ['role-edit','Chỉnh sửa vai trò',null,'role'],
            ['role-permission','Cấp quyền vai trò',null,'role'],
            ['role-delete', 'Xoá vai trò',null,'role'],
            ['role-export', 'Export vai trò',null,'role'],

            ['permission-group','Nhóm quyền','el_permission_type',null],
            ['permission-group-create','Thêm nhóm quyền',null,'permission-group'],
            ['permission-group-edit','Chỉnh sửa nhóm quyền',null,'permission-group'],
            ['permission-group-delete', 'Xoá nhóm quyền',null,'permission-group'],

//            ['permission-user','Phân quyền người dùng','el_profile',null],
//            ['permission-user-permission','Phân quyền',null,'permission-user'],
//            ['permission-user-import','Import',null,'permission-user'],
//            ['permission-user-export', 'Export',null,'permission-user'],

            ['category-unit','Quản lý danh mục đơn vị','el_unit',null],
            ['category-unit-create','Thêm đơn vị',null,'category-unit'],
            ['category-unit-edit','Chỉnh sửa đơn vị',null,'category-unit'],
            ['category-unit-delete', 'Xoá đơn vị',null,'category-unit'],
            ['category-unit-import', 'Import đơn vị',null,'category-unit'],
            ['category-unit-export', 'Export đơn vị',null,'category-unit'],

            ['category-area','Quản lý miền, khu, vùng','el_area',null],
            ['category-area-create','Thêm miền, khu, vùng',null,'category-area'],
            ['category-area-edit','Chỉnh sửa miền, khu, vùng',null,'category-area'],
            ['category-area-delete', 'Xoá miền, khu, vùng',null,'category-area'],

            ['category-unit-type','Quản lý loại đơn vị','el_unit_type',null],
            ['category-unit-type-create','Thêm loại đơn vị',null,'category-unit-type'],
            ['category-unit-type-edit','Chỉnh sửa loại đơn vị',null,'category-unit-type'],
            ['category-unit-type-delete', 'Xoá loại đơn vị',null,'category-unit-type'],

            ['category-titles','Quản lý chức danh','el_titles',null],
            ['category-titles-create','Thêm chức danh',null,'category-titles'],
            ['category-titles-edit','Chỉnh sửa chức danh',null,'category-titles'],
            ['category-titles-delete', 'Xoá chức danh',null,'category-titles'],
            ['category-titles-import', 'Import chức danh',null,'category-titles'],
            ['category-titles-export', 'Export chức danh',null,'category-titles'],

            ['category-title-rank','Quản lý cấp bậc chức danh','el_title_rank',null],
            ['category-title-rank-create','Thêm cấp bậc chức danh',null,'category-title-rank'],
            ['category-title-rank-edit','Chỉnh sửa cấp bậc chức danh',null,'category-title-rank'],
            ['category-title-rank-delete', 'Xoá cấp bậc chức danh',null,'category-title-rank'],
            ['category-title-rank-isopend', 'Bật/tắt cấp bậc chức danh',null,'category-title-rank'],

            ['category-cert','Quản lý trình độ','el_cert',null],
            ['category-cert-create','Thêm trình độ',null,'category-cert'],
            ['category-cert-edit','Chỉnh sửa trình độ',null,'category-cert'],
            ['category-cert-delete', 'Xoá trình độ',null,'category-cert'],

            ['category-training-program','Quản lý chương trình đào tạo','el_training_program',null],
            ['category-training-program-create','Thêm chương trình đào tạo',null,'category-training-program'],
            ['category-training-program-edit','Chỉnh sửa chương trình đào tạo',null,'category-training-program'],
            ['category-training-program-delete', 'Xoá chương trình đào tạo',null,'category-training-program'],
            ['category-training-program-export', 'Export chương trình đào tạo',null,'category-training-program'],

            ['category-level-subject','Quản lý cấp độ','el_level_subject',null],
            ['category-level-subject-create','Thêm cấp độ',null,'category-level-subject'],
            ['category-level-subject-edit','Chỉnh sửa cấp độ',null,'category-level-subject'],
            ['category-level-subject-delete', 'Xoá cấp độ',null,'category-level-subject'],
            ['category-level-subject-export', 'Export cấp độ',null,'category-level-subject'],

            ['category-subject','Quản lý tài liệu','el_subject',null],
            ['category-subject-create','Thêm tài liệu',null,'category-subject'],
            ['category-subject-edit','Chỉnh sửa tài liệu',null,'category-subject'],
            ['category-subject-delete', 'Xoá tài liệu',null,'category-subject'],
            ['category-subject-import', 'Import tài liệu',null,'category-subject'],
            ['category-subject-export', 'Export tài liệu',null,'category-subject'],

            ['category-training-location','Quản lý địa điểm đào tạo','el_training_location',null],
            ['category-training-location-create','Thêm địa điểm đào tạo',null,'category-training-location'],
            ['category-training-location-edit','Chỉnh sửa địa điểm đào tạo',null,'category-training-location'],
            ['category-training-location-delete', 'Xoá địa điểm đào tạo',null,'category-training-location'],

            ['category-training-form','Quản lý loại hình đào tạo','el_training_form',null],
            ['category-training-form-create','Thêm loại hình đào tạo',null,'category-training-form'],
            ['category-training-form-edit','Chỉnh sửa loại hình đào tạo',null,'category-training-form'],
            ['category-training-form-delete', 'Xoá loại hình đào tạo',null,'category-training-form'],

            ['category-training-type','Quản lý Hình thức đào tạo','el_training_type',null],
            ['category-training-type-create','Thêm Hình thức đào tạo',null,'category-training-type'],
            ['category-training-type-edit','Chỉnh sửa Hình thức đào tạo',null,'category-training-type'],
            /*['category-training-type-delete', 'Xoá Hình thức đào tạo',null,'category-training-type'],*/

            ['category-quiz-type','Quản lý loại kỳ thi','el_quiz_type',null],
            ['category-quiz-type-create','Thêm loại kỳ thi',null,'category-quiz-type'],
            ['category-quiz-type-edit','Chỉnh sửa loại kỳ thi',null,'category-quiz-type'],
            ['category-quiz-type-delete', 'Xoá loại kỳ thi',null,'category-quiz-type'],

            ['category-training-cost','Quản lý chi phí đào tạo','el_training_cost',null],
            ['category-training-cost-create','Thêm chi phí đào tạo',null,'category-training-cost'],
            ['category-training-cost-edit','Chỉnh sửa chi phí đào tạo',null,'category-training-cost'],
            ['category-training-cost-delete', 'Xoá chi phí đào tạo',null,'category-training-cost'],

            ['category-student-cost','Quản lý chi phí học viên','el_student_cost',null],
            ['category-student-cost-create','Thêm chi phí học viên',null,'category-student-cost'],
            ['category-student-cost-edit','Chỉnh sửa chi phí học viên',null,'category-student-cost'],
            ['category-student-cost-delete', 'Xoá chi phí học viên',null,'category-student-cost'],

            ['commit-month','Khung tài trợ chi phí và thời gian cam kết','el_commitment',null],
            ['commit-month-create','Thêm Khung tài trợ chi phí và thời gian cam kết',null,'commit-month'],
            ['commit-month-edit','Chỉnh sửa Khung tài trợ chi phí và thời gian cam kết',null,'commit-month'],
            ['commit-month-delete', 'Xoá Khung tài trợ chi phí và thời gian cam kết',null,'commit-month'],

            ['category-teacher','Quản lý giảng viên','el_training_teacher',null],
            ['category-teacher-create','Thêm giảng viên',null,'category-teacher'],
            ['category-teacher-edit','Chỉnh sửa giảng viên',null,'category-teacher'],
            ['category-teacher-delete', 'Xoá giảng viên',null,'category-teacher'],
            ['category-teacher-import', 'Import giảng viên',null,'category-teacher'],
            ['category-teacher-export', 'Export giảng viên',null,'category-teacher'],

            ['category-teacher-type','Quản lý loại giảng viên','el_teacher_type',null],
            ['category-teacher-type-create','Thêm loại giảng viên',null,'category-teacher-type'],
            ['category-teacher-type-edit','Chỉnh sửa loại giảng viên',null,'category-teacher-type'],
            ['category-teacher-type-delete', 'Xoá loại giảng viên',null,'category-teacher-type'],

            ['category-partner','Quản lý đối tác','el_training_partner',null],
            ['category-partner-create','Thêm đối tác',null,'category-partner'],
            ['category-partner-edit','Chỉnh sửa đối tác',null,'category-partner'],
            ['category-partner-delete', 'Xoá đối tác',null,'category-partner'],
            ['category-partner-export', 'Export đối tác',null,'category-partner'],

            ['category-province','Quản lý tỉnh thành','el_province',null],
            ['category-province-create','Thêm tỉnh thành',null,'category-province'],
            ['category-province-edit','Chỉnh sửa tỉnh thành',null,'category-province'],
            ['category-province-delete', 'Xoá tỉnh thành',null,'category-province'],
            ['category-province-import', 'Import tỉnh thành',null,'category-province'],

            ['category-district','Quản lý quận huyện','el_district',null],
            ['category-district-create','Thêm quận huyện',null,'category-district'],
            ['category-district-edit','Chỉnh sửa quận huyện',null,'category-district'],
            ['category-district-delete', 'Xoá quận huyện',null,'category-district'],

            ['category-absent','Quản lý Loại nghỉ','el_absent',null],
            ['category-absent-create','Thêm Loại nghỉ',null,'category-absent'],
            ['category-absent-edit','Chỉnh sửa Loại nghỉ',null,'category-absent'],
            ['category-absent-delete', 'Xoá Loại nghỉ',null,'category-absent'],

            ['category-discipline','Quản lý Danh sách vi phạm','el_discipline',null],
            ['category-discipline-create','Thêm Danh sách vi phạm',null,'category-discipline'],
            ['category-discipline-edit','Chỉnh sửa Danh sách vi phạm',null,'category-discipline'],
            ['category-discipline-delete', 'Xoá Danh sách vi phạm',null,'category-discipline'],

            ['category-absent_reason','Quản lý Lý do vắng mặt','el_absent_reason',null],
            ['category-absent_reason-create','Thêm Lý do vắng mặt',null,'category-absent_reason'],
            ['category-absent_reason-edit','Chỉnh sửa Lý do vắng mặt',null,'category-absent_reason'],
            ['category-absent_reason-delete', 'Xoá Lý do vắng mặt',null,'category-absent_reason'],

            /*['category-capabilities-group','Quản lý nhóm năng lực',1,null],
            ['category-capabilities-group-create','Thêm nhóm năng lực',null,'category-capabilities-group'],
            ['category-capabilities-group-edit','Chỉnh sửa nhóm năng lực',null,'category-capabilities-group'],
            ['category-capabilities-group-delete', 'Xoá nhóm năng lực',null,'category-capabilities-group'],

            ['category-capabilities-category','Quản lý danh mục năng lực',1,null],
            ['category-capabilities-category-create','Thêm danh mục năng lực',null,'category-capabilities-category'],
            ['category-capabilities-category-edit','Chỉnh sửa danh mục năng lực',null,'category-capabilities-category'],
            ['category-capabilities-category-delete', 'Xoá danh mục năng lực',null,'category-capabilities-category'],

            ['category-capabilities','Quản lý khung năng lực',1,null],
            ['category-capabilities-create','Thêm khung năng lực',null,'category-capabilities'],
            ['category-capabilities-edit','Chỉnh sửa khung năng lực',null,'category-capabilities'],
            ['category-capabilities-delete', 'Xoá khung năng lực',null,'category-capabilities'],

            ['category-capabilities-title','Quản lý khung năng lực theo chức danh',1,null],
            ['category-capabilities-title-create','Thêm khung năng lực theo chức danh',null,'category-capabilities-title'],
            ['category-capabilities-title-edit','Chỉnh sửa khung năng lực theo chức danh',null,'category-capabilities-title'],
            ['category-capabilities-title-delete', 'Xoá khung năng lực theo chức danh',null,'category-capabilities-title'],

            ['category-capabilities-group-percent','Quản lý nhóm phần trăm',1,null],
            ['category-capabilities-group-percent-create','Thêm nhóm phần trăm',null,'category-capabilities-group-percent'],
            ['category-capabilities-group-percent-edit','Chỉnh sửa nhóm phần trăm',null,'category-capabilities-group-percent'],
            ['category-capabilities-group-percent-delete', 'Xoá nhóm phần trăm',null,'category-capabilities-group-percent'],*/

            ['user','Người dùng','el_profile',null],
            ['user-create','Thêm người dùng',null,'user'],
            ['user-edit','Chỉnh sửa người dùng',null,'user'],
            ['user-delete', 'Xoá người dùng',null,'user'],
            ['user-view-training-process', 'Xem quá trình đào tạo',null,'user'],
            ['user-view-quiz-result', 'Xem kết quả thi',null,'user'],
            ['user-view-roadmap', 'Xem chương trình khung',null,'user'],
            ['user-view-career-roadmap', 'Xem lộ trình nghề nghiệp',null,'user'],
            ['user-view-working-process', 'Xem quá trình công tác',null,'user'],
            ['user-view-training-program-learned', 'Xem chủ đề đã học',null,'user'],
            ['user-view-training-by-title', 'Xem lộ trình đào tạo',null,'user'],
            ['user-approve-change-info', 'Duyệt đổi thông tin',null,'user'],
            ['user-import', 'Import người dùng',null,'user'],
            ['user-export', 'Export người dùng',null,'user'],

            /*['capabilities-review','Đánh giá khung năng lực',1,null],
            ['capabilities-review-create','Tạo đánh giá khung năng lực',null,'capabilities-review'],
            ['capabilities-review-edit','Chỉnh sửa đánh giá khung năng lực',null,'capabilities-review'],
            ['capabilities-review-delete', 'Xoá đánh giá khung năng lực',null,'capabilities-review'],
            ['capabilities-review-send', 'Gửi đánh giá khung năng lực',null,'capabilities-review'],

            ['capabilities-result','Xây dựng kế hoạch đào tạo',1,null],
            ['capabilities-result-create','Thêm xây dựng kế hoạch đào tạo',null,'capabilities-result'],
            ['capabilities-result-edit','Chỉnh sửa xây dựng kế hoạch đào tạo',null,'capabilities-result'],
            ['capabilities-result-delete', 'Xoá xây dựng kế hoạch đào tạo',null,'capabilities-result'],
            ['capabilities-result-send', 'Gửi xây dựng kế hoạch đào tạo',null,'capabilities-result'],

            ['potential','Nhân sự tiềm năng',1,null],
            ['potential-create','Thêm nhân sự tiềm năng',null,'potential'],
            ['potential-edit','Chỉnh sửa nhân sự tiềm năng',null,'potential'],
            ['potential-delete', 'Xoá nhân sự tiềm năng',null,'potential'],
            ['potential-export', 'Xuất file nhân sự tiềm năng',null,'potential'],
            ['potential-kpi', 'Xem danh sách KPI',null,'potential'],
            ['potential-roadmap','Xem chương trình khung nhân sự tiềm năng',null,'potential'],
            ['potential-roadmap-create','Thêm chương trình khung nhân sự tiềm năng',null,'potential'],
            ['potential-roadmap-edit','Chỉnh sửa chương trình khung nhân sự tiềm năng',null,'potential'],
            ['potential-roadmap-delete', 'Xoá chương trình khung nhân sự tiềm năng',null,'potential'],

            ['convert-titles','Quản lý chuyển đổi chức danh',1,null],
            ['convert-titles-evaluate', 'Đánh giá chuyển đổi chức danh',null,'convert-titles'],
            ['convert-titles-roadmap','Xem chương trình khung chuyển đổi chức danh',null,'convert-titles'],
            ['convert-titles-roadmap-create','Thêm chương trình khung chuyển đổi chức danh',null,'convert-titles'],
            ['convert-titles-roadmap-edit','Chỉnh sửa chương trình khung chuyển đổi chức danh',null,'convert-titles'],
            ['convert-titles-roadmap-delete', 'Xoá chương trình khung chuyển đổi chức danh',null,'convert-titles'],
            ['convert-titles-review','Xem mẫu đánh giá chuyển đổi chức danh',null,'convert-titles'],
            ['convert-titles-review-create','Thêm mẫu đánh giá chuyển đổi chức danh',null,'convert-titles'],
            ['convert-titles-review-edit','Chỉnh sửa mẫu đánh giá chuyển đổi chức danh',null,'convert-titles'],
            ['convert-titles-review-delete', 'Xoá mẫu đánh giá chuyển đổi chức danh',null,'convert-titles'],*/

            // ['feedback','Quản lý phản hồi',1,null],
            // ['feedback-create','Thêm phản hồi',null,'feedback'],
            // ['feedback-edit','Chỉnh sửa phản hồi',null,'feedback'],
            // ['feedback-delete', 'Xoá phản hồi',null,'feedback'],

            ['forum','Quản lý diễn đàn','el_forum_category',null],
            ['forum-create','Thêm diễn đàn',null,'forum'],
            ['forum-edit','Chỉnh sửa diễn đàn',null,'forum'],
            ['forum-delete', 'Xoá diễn đàn',null,'forum'],
            ['forum-status', 'Bật/Tắt diễn đàn',null,'forum'],
            ['forum-approve-post', 'Duyệt bài đăng',null,'forum'],
            /*['forum-send-post', 'Gửi bài viết',null,'forum'],
            ['forum-delete-post', 'Xoá bài viết',null,'forum'],
            ['forum-delete-comment', 'Xoá bình luận',null,'forum'],*/

            ['forum_thread','Bài viết','el_forum_thread',null],
            ['forum_thread-create','Thêm Bài viết',null,'forum_thread'],
            ['forum_thread-edit','Sửa Bài viết',null,'forum_thread'],
            ['forum_thread-remove','Xóa Bài viết',null,'forum_thread'],

            ['suggest','Quản lý góp ý','el_suggest',null],
            ['suggest-comment','Bình luận góp ý',null,'suggest'],

            ['rating-template','Mẫu đánh giá hiệu quả đào tạo','el_rating_template',null],
            ['rating-template-create','Thêm mẫu đánh giá hiệu quả đào tạo',null,'rating-template'],
            ['rating-template-edit','Chỉnh sửa mẫu đánh giá hiệu quả đào tạo',null,'rating-template'],
            ['rating-template-delete', 'Xoá mẫu đánh giá hiệu quả đào tạo',null,'rating-template'],
            /*['rating-template-view-result', 'Xem kết quả đánh giá sau khóa học',null,'rating-template'],*/

            /*['plan-app-template','Mẫu đánh giá hiệu quả đào tạo','el_plan_app_template',null],
            ['plan-app-template-create','Thêm mẫu đánh giá Đánh giá hiệu quả đào tạo',null,'plan-app-template'],
            ['plan-app-template-edit','Chỉnh sửa mẫu đánh giá Đánh giá hiệu quả đào tạo',null,'plan-app-template'],
            ['plan-app-template-delete', 'Xoá đánh mẫu giá Đánh giá hiệu quả đào tạo',null,'plan-app-template'],*/

            ['rating-levels','Tổ chức đánh giá','el_rating_levels',null],
            ['rating-levels-create','Thêm kỳ đánh giá đào tạo',null,'rating-levels'],
            ['rating-levels-edit','Sửa kỳ đánh giá đào tạo',null,'rating-levels'],
            ['rating-levels-delete','Xóa kỳ đánh giá đào tạo',null,'rating-levels'],
            ['rating-levels-register','Thêm HV kỳ đánh giá đào tạo',null,'rating-levels'],
            ['rating-levels-setting','Thiết lập kỳ đánh giá đào tạo',null,'rating-levels'],
            ['rating-levels-result','Xem/Đánh giá kỳ đánh giá đào tạo',null,'rating-levels'],

            ['survey','Khảo sát','el_survey',null],
            ['survey-create','Thêm khảo sát',null,'survey'],
            ['survey-edit','Chỉnh sửa khảo sát',null,'survey'],
            ['survey-delete', 'Xoá khảo sát',null,'survey'],
            ['survey-template','Mẫu khảo sát',null,'survey'],
            ['survey-template-create','Thêm mẫu khảo sát',null,'survey'],
            ['survey-template-edit','Chỉnh sửa mẫu khảo sát',null,'survey'],
            ['survey-template-delete', 'Xoá mẫu khảo sát',null,'survey'],
            ['survey-status','Bật/Tắt khảo sát',null,'survey'],
            ['survey-view-report','Xem báo cáo chi tiết khảo sát',null,'survey'],
            ['survey-export-report', 'Xuất báo cáo tổng hợp khảo sát',null,'survey'],

            ['plan-suggest','Đề xuất kế hoạch đào tạo','el_plan_suggest',null],
            ['plan-suggest-create','Thêm đề xuất kế hoạch đào tạo',null,'plan-suggest'],
            ['plan-suggest-edit','Chỉnh sửa đề xuất kế hoạch đào tạo',null,'plan-suggest'],
            ['plan-suggest-delete', 'Xoá đề xuất kế hoạch đào tạo',null,'plan-suggest'],
            ['plan-suggest-approve', 'Duyệt/Từ chối đề xuất kế hoạch đào tạo',null,'plan-suggest'],
            ['plan-suggest-export', 'Xuất đề xuất kế hoạch đào tạo',null,'plan-suggest'],

            ['career-roadmap','Lộ trình nghề nghiệp','career_roadmap',null],
            ['career-roadmap-create','Thêm lộ trình nghề nghiệp',null,'career-roadmap'],
            ['career-roadmap-edit','Sửa lộ trình nghề nghiệp',null,'career-roadmap'],
            ['career-roadmap-delete','Xóa lộ trình nghề nghiệp',null,'career-roadmap'],

            ['training-plan','Kế hoạch đào tạo năm','el_training_plan',null],
            ['training-plan-create','Thêm kế hoạch đào tạo năm',null,'training-plan'],
            ['training-plan-edit','Chỉnh sửa kế hoạch đào tạo năm',null,'training-plan'],
            ['training-plan-delete', 'Xoá kế hoạch đào tạo năm',null,'training-plan'],
            ['training-plan-approved', 'Duyệt/Từ chối kế hoạch đào tạo năm',null,'training-plan'],
            ['training-plan-detail','Chi tiết kế hoạch đào tạo năm',null,'training-plan'],
            ['training-plan-detail-create','Thêm chi tiết kế hoạch đào tạo năm',null,'training-plan'],
            ['training-plan-detail-edit','Chỉnh sửa chi tiết kế hoạch đào tạo năm',null,'training-plan'],
            ['training-plan-detail-delete', 'Xoá chi tiết kế hoạch đào tạo năm',null,'training-plan'],

            ['online-course','Khóa học online','el_online_course',null],
            ['online-course-create','Thêm khóa học online',null,'online-course'],
            ['online-course-edit','Chỉnh sửa khóa học online',null,'online-course'],
            ['online-course-delete', 'Xoá khóa học online',null,'online-course'],
            ['online-course-approve', 'Duyệt/Từ chối khóa học online',null,'online-course'],
            ['online-course-status', 'Bật/Tắt khóa học online',null,'online-course'],
            ['online-course-duplicate', 'Sao chép khóa học online',null,'online-course'],
            ['online-course-register','Ghi danh khóa học online','el_online_register',null],
            ['online-course-register-create','Thêm ghi danh khóa học online',null,'online-course-register'],
            ['online-course-register-edit','Chỉnh sửa ghi danh khóa học online',null,'online-course-register'],
            ['online-course-register-delete', 'Xoá ghi danh khóa học online',null,'online-course-register'],
            ['online-course-register-approve', 'Duyệt/Từ chối ghi danh khóa học online',null,'online-course-register'],
            ['online-course-result','Kết quả đào tạo khóa học online',null,'online-course'],
            ['online-course-rating-result','Kết quả đánh giá khóa học online',null,'online-course'],
            ['online-course-rating-level-result','Kết quả đánh giá cấp độ khóa học online',null,'online-course'],

            ['offline-course','Khóa học tập trung','el_offline_course',null],
            ['offline-course-create','Thêm khóa học tập trung',null,'offline-course'],
            ['offline-course-edit','Chỉnh sửa khóa học tập trung',null,'offline-course'],
            ['offline-course-delete', 'Xoá khóa học tập trung',null,'offline-course'],
            ['offline-course-approve', 'Duyệt/Từ chối khóa học tập trung',null,'offline-course'],
            ['offline-course-status', 'Bật/Tắt khóa học tập trung',null,'offline-course'],
            ['offline-course-duplicate', 'Sao chép khóa học tập trung',null,'offline-course'],

            ['offline-course-register','Ghi danh khóa học tập trung','el_offline_register',null],
            ['offline-course-register-create','Thêm ghi danh khóa học tập trung',null,'offline-course-register'],
            ['offline-course-register-delete','Xóa ghi danh khóa học tập trung',null,'offline-course-register'],
            ['offline-course-register-approve', 'Duyệt/Từ chối ghi danh khóa học tập trung',null,'offline-course-register'],
            ['offline-course-register-import', 'Import ghi danh khóa học tập trung',null,'offline-course-register'],
            ['offline-course-register-export', 'Export ghi danh khóa học tập trung',null,'offline-course-register'],

            ['offline-course-teacher','Giảng viên khóa học tập trung',null,'offline-course'],
            ['offline-course-teacher-create','Thêm giảng viên khóa học tập trung',null,'offline-course'],
            ['offline-course-teacher-delete','Xóa giảng viên khóa học tập trung',null,'offline-course'],
            ['offline-course-attendance','Điểm danh khóa học tập trung',null,'offline-course'],
            ['offline-course-result','Kết quả đào tạo khóa học tập trung',null,'offline-course'],
            ['offline-course-result-create','Thêm kết quả đào tạo khóa học tập trung',null,'offline-course'],
            ['offline-course-rating-result','Kết quả đánh giá khóa học tập trung',null,'offline-course'],
            ['offline-course-rating-level-result','Kết quả đánh giá cấp độ khóa học tập trung',null,'offline-course'],

            /*['training-unit','Đào tạo đơn vị',1,null],
            ['training-unit-offline-course','Khóa học tập trung',null,'training-unit'],
           ['training-unit-offline-course-create','Thêm khóa học tập trung',null,'training-unit'],
            ['training-unit-offline-course-edit','Chỉnh sửa khóa học tập trung',null,'training-unit'],
            ['training-unit-offline-course-delete', 'Xoá khóa học tập trung',null,'training-unit'],
            ['training-unit-offline-course-approve', 'Duyệt/Từ chối khóa học tập trung',null,'training-unit'],
            ['training-unit-offline-course-status', 'Bật/Tắt khóa học tập trung',null,'training-unit'],
            ['training-unit-offline-course-register','Ghi danh khóa học tập trung',null,'training-unit'],
            ['training-unit-offline-course-register-create','Thêm ghi danh khóa học tập trung',null,'training-unit'],
            ['training-unit-offline-course-register-approve', 'Duyệt/Từ chối ghi danh khóa học tập trung',null,'training-unit'],
            ['training-unit-offline-course-teacher','Giảng viên khóa học tập trung',null,'training-unit'],
            ['training-unit-offline-course-teacher-create','Thêm giảng viên khóa học tập trung',null,'training-unit'],
            ['training-unit-offline-course-attendance','Điểm danh khóa học tập trung',null,'training-unit'],
            ['training-unit-offline-course-result-create','Thêm kết quả đào tạo khóa học tập trung',null,'training-unit'],
            ['training-unit-quiz','Kỳ thi',null,'training-unit'],
            ['training-unit-quiz-create','Thêm kỳ thi',null,'training-unit'],
            ['training-unit-quiz-edit','Chỉnh sửa kỳ thi',null,'training-unit'],
            ['training-unit-quiz-delete', 'Xoá kỳ thi',null,'training-unit'],
            ['training-unit-quiz-view-result', 'Cho/Tắt xem kết quả',null,'training-unit'],
            ['training-unit-quiz-status', 'Bật/Tắt kỳ thi',null,'training-unit'],
            ['training-unit-quiz-copy', 'Sao chép kỳ thi',null,'training-unit'],
            ['training-unit-quiz-add-question', 'Thêm câu hỏi vào kỳ thi',null,'training-unit'],
            ['training-unit-quiz-register', 'Ghi danh thí sinh nội bộ',null,'training-unit'],
            ['training-unit-quiz-register-user-secondary', 'Xem ghi danh người thi ngoài',null,'training-unit'],
            ['training-unit-quiz-result', 'Kết quả kỳ thi',null,'training-unit'],
            ['training-unit-quiz-update-grade', 'Sửa điểm kỳ thi',null,'training-unit'],
            ['training-unit-quiz-update-reexamine', 'Sửa điểm phúc khảo kỳ thi',null,'training-unit'],
            ['training-unit-quiz-export', 'Xuất kết quả kỳ thi',null,'training-unit'],
            ['training-unit-quiz-print-exam', 'In đề kỳ thi',null,'training-unit'],*/

            ['indemnify','Quản lý bồi hoàn','el_indemnify',null],
            ['indemnify-update-committed-date','Chỉnh sửa số ngày cam kết',null,'indemnify'],

            ['certificate-template','Mẫu chứng chỉ','el_certificate',null],
            ['certificate-template-create','Thêm mẫu chứng chỉ',null,'certificate-template'],
            ['certificate-template-edit','Chỉnh sửa mẫu chứng chỉ',null,'certificate-template'],

            ['training-roadmap','Chương trình khung','el_trainingroadmap',null],
            ['training-roadmap-create','Thêm chương trình khung',null,'training-roadmap'],
            ['training-roadmap-edit','Chỉnh sửa chương trình khung',null,'training-roadmap'],
            ['training-roadmap-delete', 'Xoá chương trình khung',null,'training-roadmap'],
            ['training-roadmap-export', 'Export chương trình khung',null,'training-roadmap'],
            ['training-roadmap-import', 'Import chương trình khung',null,'training-roadmap'],

//            ['plan-app','Quản lý đánh giá hiệu quả đào tạo','el_plan_app',null],

            ['quiz','Kỳ thi','el_quiz',null],
            ['quiz-create','Thêm kỳ thi',null,'quiz'],
            ['quiz-edit','Chỉnh sửa kỳ thi',null,'quiz'],
            ['quiz-delete', 'Xoá kỳ thi',null,'quiz'],
            ['quiz-view-result', 'Cho/Tắt xem kết quả',null,'quiz'],
            ['quiz-approve', 'Duyệt/Từ chối kỳ thi',null,'quiz'],
            ['quiz-status', 'Bật/Tắt kỳ thi',null,'quiz'],
            ['quiz-copy', 'Sao chép kỳ thi',null,'quiz'],
            ['quiz-add-question', 'Thêm câu hỏi vào kỳ thi',null,'quiz'],
            ['quiz-register', 'Ghi danh thí sinh nội bộ',null,'quiz'],
            ['quiz-register-user-secondary', 'Ghi danh thí sinh bên ngoài',null,'quiz'],
            ['quiz-result', 'Kết quả kỳ thi',null,'quiz'],
            ['quiz-update-grade', 'Sửa điểm kỳ thi',null,'quiz'],
            ['quiz-update-reexamine', 'Sửa điểm phúc khảo kỳ thi',null,'quiz'],
            ['quiz-export', 'Xuất kết quả kỳ thi',null,'quiz'],
            ['quiz-print-exam', 'In đề kỳ thi',null,'quiz'],
            ['quiz-grading', 'Chấm điểm kỳ thi',null,'quiz'],

            ['quiz-category-question','Ngân hàng câu hỏi','el_question_category',null],
            ['quiz-category-question-create','Thêm danh mục ngân hàng câu hỏi',null,'quiz-category-question'],
            ['quiz-category-question-edit','Chỉnh sửa danh mục ngân hàng câu hỏi',null,'quiz-category-question'],
            ['quiz-category-question-delete', 'Xoá danh mục ngân hàng câu hỏi',null,'quiz-category-question'],
            ['quiz-category-question-permission', 'Phân quyền danh mục ngân hàng câu hỏi',null,'quiz-category-question'],

            ['quiz-question','Câu hỏi','el_question',null],
            ['quiz-question-create','Thêm câu hỏi',null,'quiz-question'],
            ['quiz-question-edit','Chỉnh sửa câu hỏi',null,'quiz-question'],
            ['quiz-question-delete', 'Xoá câu hỏi',null,'quiz-question'],
            ['quiz-question-approve', 'Duyệt/Từ chối câu hỏi',null,'quiz-question'],
            ['quiz-question-import', 'Import câu hỏi',null,'quiz-question'],
            ['quiz-question-export', 'Export câu hỏi',null,'quiz-question'],

            ['quiz-user-secondary','Thí sinh bên ngoài','el_quiz_user_secondary',null],
            ['quiz-user-secondary-create','Thêm thí sinh bên ngoài',null,'quiz-user-secondary'],
            ['quiz-user-secondary-edit','Chỉnh sửa thí sinh bên ngoài',null,'quiz-user-secondary'],
            ['quiz-user-secondary-delete', 'Xoá thí sinh bên ngoài',null,'quiz-user-secondary'],

            ['quiz-template','Cơ cấu đề thi','el_quiz_templates',null],
            ['quiz-template-create','Thêm Cơ cấu đề thi',null,'quiz-template'],
            ['quiz-template-approved','Duyệt/Từ chối Cơ cấu đề thi',null,'quiz-template'],
            ['quiz-template-open','Bật/Tắt Cơ cấu đề thi',null,'quiz-template'],
            ['quiz-template-edit','Chỉnh sửa Cơ cấu đề thi',null,'quiz-template'],
            ['quiz-template-delete', 'Xoá Cơ cấu đề thi',null,'quiz-template'],
            ['quiz-template-rank', 'Thêm xếp loại Cơ cấu đề thi',null,'quiz-template'],
            ['quiz-template-setting', 'Thêm tùy chỉnh Cơ cấu đề thi',null,'quiz-template'],
            ['quiz-template-question', 'Thêm câu hỏi Cơ cấu đề thi',null,'quiz-template'],

            ['quiz-setting-alert','Thiết lập cảnh báo','el_quiz_user_secondary',null],
            ['quiz-setting-alert-create','Thêm Thiết lập cảnh báo',null,'quiz-setting-alert'],

            ['quiz-dashboard','Thống kê kì thi',1,null],
            ['quiz-dashboard-watch','Xem Thống kê kì thi',null,'quiz-dashboard'],

            ['quiz-history','Lịch sử thi tuyển thí sinh nội bộ',1,null],
            ['quiz-history-watch','Xem Lịch sử thi tuyển thí sinh nội bộ',null,'quiz-history'],

            ['quiz-history-user-second','Lịch sử thi tuyển thí sinh bên ngoài',1,null],
            ['quiz-history-user-second-watch','Xem Lịch sử thi tuyển thí sinh bên ngoài',null,'quiz-history-user-second'],

            ['libraries-category','Danh mục thư viện','el_libraries_category',null],
            ['libraries-category-create','Thêm danh mục thư viện',null,'libraries-category'],
            ['libraries-category-edit','Chỉnh sửa danh mục thư viện',null,'libraries-category'],
            ['libraries-category-delete', 'Xoá danh mục thư viện',null,'libraries-category'],

            ['libraries-book','Sách trong thư viện','el_libraries',null],
            ['libraries-book-create','Thêm sách trong thư viện',null,'libraries-book'],
            ['libraries-book-edit','Chỉnh sửa sách trong thư viện',null,'libraries-book'],
            ['libraries-book-delete', 'Xoá sách trong thư viện',null,'libraries-book'],

            ['libraries-book-register', 'Quản lý mượn sách trong thư viện','el_register_book',null],
            ['libraries-book-register-approve', 'Duyệt mượn sách trong thư viện',null,'libraries-book-register'],
            ['libraries-book-register-borrow', 'Lấy/trả sách trong thư viện',null,'libraries-book-register'],
            ['libraries-book-register-delete', 'Xóa mượn sách trong thư viện',null,'libraries-book-register'],

            ['libraries-ebook','Sách điện tử trong thư viện','el_libraries',null],
            ['libraries-ebook-create','Thêm sách điện tử trong thư viện',null,'libraries-ebook'],
            ['libraries-ebook-edit','Chỉnh sửa sách điện tử trong thư viện',null,'libraries-ebook'],
            ['libraries-ebook-delete', 'Xoá sách điện tử trong thư viện',null,'libraries-ebook'],

            ['libraries-document','Tài liệu trong thư viện','el_libraries',null],
            ['libraries-document-create','Thêm tài liệu trong thư viện',null,'libraries-document'],
            ['libraries-document-edit','Chỉnh sửa tài liệu trong thư viện',null,'libraries-document'],
            ['libraries-document-delete', 'Xoá tài liệu trong thư viện',null,'libraries-document'],

            ['libraries-video','Video trong thư viện','el_libraries',null],
            ['libraries-video-create','Thêm video trong thư viện',null,'libraries-video'],
            ['libraries-video-edit','Chỉnh sửa video trong thư viện',null,'libraries-video'],
            ['libraries-video-delete', 'Xoá video trong thư viện',null,'libraries-video'],

            ['libraries-audiobook','Sách nói trong thư viện','el_libraries',null],
            ['libraries-audiobook-create','Thêm sách nói trong thư viện',null,'libraries-audiobook'],
            ['libraries-audiobook-edit','Chỉnh sửa sách nói trong thư viện',null,'libraries-audiobook'],
            ['libraries-audiobook-delete', 'Xoá sách nói trong thư viện',null,'libraries-audiobook'],

            ['news-category','Danh mục tin tức','el_news_category',null],
            ['news-category-create','Thêm danh mục tin tức',null,'news-category'],
            ['news-category-edit','Chỉnh sửa danh mục tin tức',null,'news-category'],
            ['news-category-delete', 'Xoá danh mục tin tức',null,'news-category'],

            ['news-list','Danh sách tin tức','el_news',null],
            ['news-list-create','Thêm danh sách tin tức',null,'news-list'],
            ['news-list-edit','Chỉnh sửa danh sách tin tức',null,'news-list'],
            ['news-list-delete', 'Xoá danh sách tin tức',null,'news-list'],
            ['news-list-status', 'Bật/Tắt danh sách tin tức',null,'news-list'],

            ['advertising-photo','Danh sách ảnh quảng cáo','el_advertising_photo',null],
            ['advertising-photo-create','Thêm',null,'advertising-photo'],
            ['advertising-photo-edit','Chỉnh sửa ',null,'advertising-photo'],
            ['advertising-photo-delete', 'Xoá',null,'advertising-photo'],

            ['news-outside-category','Danh mục tin tức chung','el_news_outside_category',null],
            ['news-outside-category-create','Thêm danh mục tin tức chung',null,'news-outside-category'],
            ['news-outside-category-edit','Chỉnh sửa danh mục tin tức chung',null,'news-outside-category'],
            ['news-outside-category-delete', 'Xoá danh mục tin tức chung',null,'news-outside-category'],

            ['news-outside-list','Danh sách tin tức chung','el_news_outside',null],
            ['news-outside-list-create','Thêm danh sách tin tức chung',null,'news-outside-list'],
            ['news-outside-list-edit','Chỉnh sửa danh sách tin tức chung',null,'news-outside-list'],
            ['news-outside-list-delete', 'Xoá danh sách tin tức chung',null,'news-outside-list'],
            ['news-outside-list-status', 'Bật/Tắt danh sách tin tức chung',null,'news-outside-list'],

            ['promotion','Tích lũy điểm thưởng','el_promotion',null],
            ['promotion-create','Thêm tích lũy điểm thưởng',null,'promotion'],
            ['promotion-edit','Chỉnh sửa tích lũy điểm thưởng',null,'promotion'],
            ['promotion-delete', 'Xoá tích lũy điểm thưởng',null,'promotion'],

            ['promotion-group','Nhóm danh mục quà tặng (Tích lũy điểm thưởng)','el_promotion_group',null],
            ['promotion-group-create','Thêm nhóm danh mục quà tặng',null,'promotion-group'],
            ['promotion-group-edit','Chỉnh sửa nhóm danh mục quà tặng',null,'promotion-group'],
            ['promotion-group-delete', 'Xoá nhóm danh mục quà tặng',null,'promotion-group'],

            ['promotion-level','Cấp bậc người dùng (Tích lũy điểm thưởng)','el_promotion_level',null],
            ['promotion-level-create','Thêm cấp bậc người dùng',null,'promotion-level'],
            ['promotion-level-edit','Chỉnh sửa cấp bậc người dùng',null,'promotion-level'],
            ['promotion-level-delete', 'Xoá cấp bậc người dùng',null,'promotion-level'],

            ['promotion-purchase-history','Lịch sừ mua (Tích lũy điểm thưởng)','el_promotion_orders',null],
            ['promotion-purchase-history-edit','Chỉnh sửa lịch sừ mua',null,'promotion-purchase-history'],

            /*['footer','Footer',1,null],
            ['footer-edit','Chỉnh sửa Footer',null,'footer'],*/

            ['logo','Logo',1,null],
            ['logo-edit','Chỉnh sửa Logo',null,'logo'],

            ['favicon','Favicon',1,null],
            ['favicon-edit','Chỉnh sửa favicon',null,'favicon'],

            ['notify','Thông báo',1,null],
            ['notify-create','Thêm thông báo',null,'notify'],
            ['notify-edit','Chỉnh sửa thông báo',null,'notify'],
            ['notify-delete', 'Xoá thông báo',null,'notify'],
            ['notify-status', 'Bật/tắt thông báo',null,'notify'],

            ['mail-template','Mẫu mail template','el_mail_template',null],
            ['mail-template-edit','Chỉnh sửa mẫu mail',null,'mail-template'],

            ['mail-history','Lịch sử gửi mail','el_mail_history',null],

            ['guide','Hướng dẫn','el_guide',null],
            ['guide-create','Thêm hướng dẫn',null,'guide'],
            ['guide-edit','Chỉnh sửa hướng dẫn',null,'guide'],
            ['guide-delete', 'Xoá hướng dẫn',null,'guide'],

            ['banner','Banner','el_slider',null],
            ['banner-create','Thêm banner',null,'banner'],
            ['banner-edit','Chỉnh sửa banner',null,'banner'],
            ['banner-delete', 'Xoá banner',null,'banner'],

            ['report','Báo cáo',1,null],
            ['report-01', 'Báo cáo số liệu công tác khảo thi',null, 'report'],
            ['report-02', 'Báo cáo số liệu điểm thi chi tiết',null, 'report'],
            ['report-03', 'Báo cáo cơ cấu đề thi',null, 'report'],
            ['report-04', 'Báo cáo tỉ lệ trả lời đúng từng câu hỏi trong ngân hàng câu hỏi',null, 'report'],
            ['report-05', 'Báo cáo học viên tham gia khóa học tập trung/trực tuyến',null, 'report'],
            ['report-06', 'Danh sách học viên của đơn vị theo chuyên đề',null, 'report'],
            ['report-07', 'Báo cáo quá trình đào tạo của nhân viên',null, 'report'],
            ['report-08', 'Tổng hợp tình hình tổ chức các khóa học nội bộ và bên ngoài',null, 'report'],
            ['report-09', 'Thống kê tình hình đào tạo nhân viên tân tuyển',null, 'report'],
            ['report-10', 'Danh sách CBNV không chấp hành nội quy đào tạo',null, 'report'],
            ['report-11', 'Thống kê Giảng viên Đào tạo (Nội bộ & bên ngoài) theo Tháng/Quý/Năm',null, 'report'],
            ['report-12', 'Thống kê chi tiết học viên theo đơn vị',null, 'report'],
            ['report-13', 'Báo cáo chi phí đào tạo theo khu vực',null, 'report'],
            ['report-14', 'Export danh mục',null, 'report'],
            ['report-15', 'Báo cáo tổng hợp kết quả theo tháp đào tạo',null, 'report'],
            ['report-17', 'Danh sách xác nhận bồi hoàn chi phí đào tạo đối với CBNV tân tuyển',null, 'report'],
            ['report-18', 'Danh sách xác nhận bồi hoàn chi phí đào tạo đối với CBNV có cam kết',null, 'report'],
            ['report-21', 'Danh sách các khóa học trực tuyến đang mở',null, 'report'],
            ['report-22', 'Danh sách các chuyên đề gộp/tách',null, 'report'],
            ['report-23', 'Thống kê tỷ lệ hoàn thành tháp đào tạo theo chức danh',null, 'report'],
            ['report-24', 'Tổng hợp tình hình tham gia đào tạo các khóa E-Learning theo đơn vị',null, 'report'],
            ['report-25', 'Tổng hợp tình hình tham gia đào tạo các khóa E-Learning theo chuyên đề',null, 'report'],
            ['report-26', 'Báo cáo thù lao giảng viên',null, 'report'],
            ['report-27', 'Báo cáo chi phí đào tạo',null, 'report'],
            ['report-28', 'Báo cáo kết quả chi tiết theo kỳ thi',null, 'report'],
            ['report-29', 'Báo cáo kết quả thực hiện so với kế hoạch quý/năm',null, 'report'],

//            ['report-01','Danh sách ký cam kết bồi hoàn',null,'report'],
//            ['report-02','Danh sách học viên tham gia các khóa đào tạo',null,'report'],
//            ['report-03','Danh sách khóa đào tạo có chi phí',null,'report'],
//            ['report-04','Danh sách học viên tham gia khóa đào tạo',null,'report'],
//            ['report-05','Báo cáo giáo vụ',null,'report'],
//            ['report-06','Báo cáo kết quả khóa học tập trung',null,'report'],
//            ['report-07','Báo cáo kết quả khóa học Elearning',null,'report'],
//            ['report-08','Báo cáo đánh giá sau khóa học',null,'report'],
//            ['report-09','Báo cáo danh sách giảng viên',null,'report'],
//            ['report-10','Báo cáo đánh giá',null,'report'],
//            ['report-11','Thống kê đăng ký tham giá khóa học',null,'report'],
//            ['report-12','Danh sách vi phạm',null,'report'],
//            ['report-13','Thống kê kết quả đào tạo',null,'report'],
//            ['report-14','Quá trình đào tạo',null,'report'],
//            ['report-15','Báo cáo chi tiết kết quả kỳ thi',null,'report'],
//            ['report-16','Báo cáo số lần thi theo nhóm câu hỏi',null,'report'],
//            ['report-17','Báo cáo lần truy cập',null,'report'],
//            ['report-18','Thống kê thí sinh trong kỳ thi theo chức danh',null,'report'],
//            ['report-19','Thống kê tỷ lệ xếp loại trong kỳ thi theo chức danh',null,'report'],
//            ['report-20','Kế hoạch tự đào tạo',null,'report'],
//            ['report-21','Tổng hợp báo cáo đào tạo nội bộ',null,'report'],
//            ['report-22','Báo cáo chi tiết thực hiện đào tạo nội bộ',null,'report'],
//            ['report-23','Báo cáo thống kê kết quả khảo sát',null,'report'],
//            ['report-24','Báo cáo tình hình đào tạo theo kênh phân phối',null,'report'],
//            ['report-25','Thống kê kết quả đào tạo theo chức danh',null,'report'],
//            ['report-26','Báo cáo đào tạo',null,'report'],
//            ['report-27','Báo cáo hiệu quả sau đào tạo',null,'report'],
            // ['report-28','Báo cáo 28',null,'report'],
            // ['report-29','Báo cáo 29',null,'report'],
            // ['report-30','Báo cáo 30',null,'report'],
            // ['report-31','Báo cáo 31',null,'report'],
            // ['report-32','Báo cáo 32',null,'report'],
            // ['report-33','Báo cáo 33',null,'report'],
            // ['report-34','Báo cáo 34',null,'report'],
            // ['report-35','Báo cáo 35',null,'report'],

            /*['commit-month','Cam kết',1,null],
            ['commit-month-create','Thêm cam kết',null,'commit-month'],
            ['commit-month-edit','Chỉnh sửa cam kết',null,'commit-month'],
            ['commit-month-delete', 'Xoá cam kết',null,'commit-month'],*/

            ['donate-point','Điểm tặng','el_donate_points',null],
            ['donate-point-create','Thêm Điểm tặng',null,'donate-point'],
            ['donate-point-edit','Chỉnh sửa Điểm tặng',null,'donate-point'],
            ['donate-point-delete', 'Xoá Điểm tặng',null,'donate-point'],
            ['donate-point-import', 'Import điểm',null,'donate-point'],
            ['donate-point-export', 'Export điểm',null,'donate-point'],
            ['donate-point-download', 'Download mẫu import',null,'donate-point'],

            ['score-view','Lượt xem (đào tạo video)','el_daily_training_setting_score_views',null],
            ['score-view-create','Thêm Lượt xem',null,'score-view'],
            ['score-view-edit','Chỉnh sửa Lượt xem',null,'score-view'],
            ['score-view-delete', 'Xoá Lượt xem',null,'score-view'],

            ['score-like','Lượt thích (đào tạo video)','el_daily_training_setting_score_like',null],
            ['score-like-create','Thêm Lượt thích',null,'score-like'],
            ['score-like-edit','Chỉnh sửa Lượt thích',null,'score-like'],
            ['score-like-delete', 'Xoá Lượt thích',null,'score-like'],

            ['score-comment','Lượt bình luận (đào tạo video)','el_daily_training_setting_score_comment',null],
            ['score-comment-create','Thêm Lượt bình luận',null,'score-comment'],
            ['score-comment-edit','Chỉnh sửa Lượt bình luận',null,'score-comment'],
            ['score-comment-delete', 'Xoá Lượt bình luận',null,'score-comment'],

            ['FAQ','Câu hỏi thường gặp','el_faq',null],
            ['FAQ-create','Thêm câu hỏi thường gặp',null,'FAQ'],
            ['FAQ-edit','Chỉnh sửa câu hỏi thường gặp',null,'FAQ'],
            ['FAQ-delete', 'Xoá câu hỏi thường gặp',null,'FAQ'],

            ['daily-training','Danh mục video','el_daily_training_category',null],
            ['daily-training-create','Thêm danh mục video',null,'daily-training'],
            ['daily-training-edit','Chỉnh sửa danh mục video',null,'daily-training'],
            ['daily-training-delete', 'Xoá danh mục video',null,'daily-training'],

            ['daily-training-video','Video',1,null],
            ['daily-training-video-acceept','Duyệt video',null,'daily-training-video'],
            ['daily-training-video-delete', 'Xoá video',null,'daily-training-video'],

            // ['daily-training-permission','Quyền danh mục video',1,null],
            // ['daily-training-permission-save','Thêm quyền danh mục video',null,'daily-training-permission'],

            ['login-image','Hình nền đăng nhập',1,null],
            ['login-image-choose','chọn hình nền đăng nhập',null,'login-image'],
            ['login-image-save','Lưu hình nền đăng nhập',null,'login-image'],

            ['setting-email','cài đăt cấu hình email',1,null],
            ['setting-email-save','Lưu cài đăt cấu hình email',null,'setting-email'],

            ['config','cài đăt cấu hình chung (LDAP)','el_config',null],
            ['config-save','Lưu cài đăt cấu hình chung',null,'config'],
            ['config-email','Cài đăt cấu hình email',null,'config'],
            ['config-email-save','Lưu cài đăt cấu hình email',null,'config'],
            ['config-point-refer','Cài đăt cấu hình điểm giới thiệu',null,'config'],
            ['config-point-refer-save','Lưu cài đăt cấu hình điểm giới thiệu',null,'config'],
            ['config-login-image','Hình nền đăng nhập',null,'config'],
            ['config-login-image-save','Lưu hình nền đăng nhập',null,'config'],
            ['config-logo','Logo',null,'config'],
            ['config-logo-save','Lưu logo',null,'config'],
            ['config-favicon','Favicon',null,'config'],
            ['config-favicon-save','Lưu favicon',null,'config'],
            ['config-app-mobile','App mobile',null,'config'],
            ['config-app-mobile-save','Lưu cài đặt App mobile',null,'config'],

            ['config-notify-send','cài đặt gửi thông báo','el_notify_send',null],
            ['config-notify-create','Thêm',null,'config-notify-send'],
            ['config-notify-delete','Xóa',null,'config-notify-send'],
            ['config-notify-edit','Sửa',null,'config-notify-send'],
            ['config-notify-enable','Bật/tắt',null,'config-notify-send'],

            ['config-notify-template','cài đặt mẫu thông báo','el_notify_template',null],
            ['config-notify-template-create','Thêm',null,'config-notify-template'],
            ['config-notify-template-edit','Sửa',null,'config-notify-template'],

            ['config-point-refer','Cài đặt điểm giới thiệu',1,null],
            ['config-point-refer-save','Lưu cài đăt điểm giới thiệu',null,'config-point-refer'],

            ['training-plain-detail','Chi tiết kế hoạch đào tạo','el_training_plan_detail',null],
            ['training-plain-detail-create','Thêm chi tiết kế hoạch đào tạo',null,'training-plain-detail'],
            ['training-plain-detail-edit','Sửa Chi tiết kế hoạch đào tạo',null,'training-plain-detail'],
            ['training-plain-detail-delete','Xóa Chi tiết kế hoạch đào tạo',null,'training-plain-detail'],

            ['virtual-classroom','Khóa học online','el_virtual_classroom',null],
            ['virtual-classroom-create','Thêm khóa học',null,'virtual-classroom'],
            ['virtual-classroom-edit','Chỉnh sửa khóa học',null,'virtual-classroom'],
            ['virtual-classroom-delete','Xóa khóa học',null,'virtual-classroom'],

            ['dashboard','Quản lý Dashboard',1,null],
            ['dashboard-unit','Quản lý Dashboard đơn vị',1,null],
            ['category-master-data','Danh mục master data',1,null],

            ['category-unit-type','Loại tổ chức','el_unit_type',null],
            ['category-unit-type-create','Thêm',null,'category-unit-type'],
            ['category-unit-type-edit','Sửa',null,'category-unit-type'],
            ['category-unit-type-delete','Xóa',null,'category-unit-type'],
            ['category-unit-type-imoprt','Import',null,'category-unit-type'],
            ['category-unit-type-export','Export',null,'category-unit-type'],

            ['approve-register','Duyệt ghi danh','1',null],

            ['quiz-register','Ghi danh thí sinh vào kỳ thi','el_quiz_register',null],
            ['quiz-register-create','Thêm thí sinh',null,'quiz-register'],
            ['quiz-register-delete','Xóa thí sinh',null,'quiz-register'],
            ['quiz-register-import','Import thí sinh',null,'quiz-register'],
            ['quiz-register-export','Export thí sinh',null,'quiz-register'],

            ['emulation-program','Chương trình thi đua','el_emulation_program',null],
            ['emulation-program-create','Thêm chương trình',null,'emulation-program'],
            ['emulation-program-edit','Chỉnh sửa chương trình',null,'emulation-program'],
            ['emulation-program-approved','Duyệt/Từ chối chương trình',null,'emulation-program'],
            ['emulation-program-open','Bật/tắt chương trình',null,'emulation-program'],
            ['emulation-program-delete','Xóa chương trình',null,'emulation-program'],
            ['emulation-program-export','Export chương trình',null,'emulation-program'],
            ['emulation-program-create-armorial','Thêm huy hiệu chương trình',null,'emulation-program'],
            ['emulation-program-create-object','Thêm đối tượng chương trình',null,'emulation-program'],
            ['emulation-program-delete-object','Xóa đối tượng chương trình',null,'emulation-program'],
            ['emulation-program-create-condition','Thêm điều kiện chương trình',null,'emulation-program'],
            ['emulation-program-delete-condition','Xóa điều kiện chương trình',null,'emulation-program'],

            ['mergesubject','Gộp chuyên đề','el_merge_subject',null],
            ['mergesubject-create','Thêm gộp chuyên đề',null,'mergesubject'],
            ['mergesubject-edit','Chỉnh sửa gộp chuyên đề',null,'mergesubject'],
            ['mergesubject-approved','Duyệt/Từ chối gộp chuyên đề',null,'mergesubject'],
            ['mergesubject-delete','Xóa gộp chuyên đề',null,'mergesubject'],

            ['splitsubject','Tách chuyên đề','el_merge_subject',null],
            ['splitsubject-create','Thêm tách chuyên đề',null,'splitsubject'],
            ['splitsubject-edit','Chỉnh sửa tách chuyên đề',null,'splitsubject'],
            ['splitsubject-approved','Duyệt/Từ chối tách chuyên đề',null,'splitsubject'],
            ['splitsubject-delete','Xóa tách chuyên đề',null,'splitsubject'],

            ['subjectcomplete','Hoàn thành quá trình đào tạo',1,null],
            ['subjectcomplete-choose-subject','Chọn chuyên đề Hoàn thành quá trình đào tạo',null,'subjectcomplete'],
            ['subjectcomplete-watch-log','Xem logs Hoàn thành quá trình đào tạo',null,'subjectcomplete'],
            ['subjectcomplete-approved','Duyệt Hoàn thành quá trình đào tạo',null,'subjectcomplete'],
            ['subjectcomplete-import','Thêm Hoàn thành quá trình đào tạo',null,'subjectcomplete'],

            ['movetrainingprocess','Chuyển quá trình đào tạo','el_move_training_process',null],
            ['movetrainingprocess-move','Chuyển quá trình đào tạo',null,'movetrainingprocess'],
            ['movetrainingprocess-edit','Sửa chuyển quá trình đào tạo',null,'movetrainingprocess'],
            ['movetrainingprocess-watch-log','Xem logs Chuyển quá trình đào tạo',null,'movetrainingprocess'],
            ['movetrainingprocess-approved','Duyệt/Từ chối Chuyển quá trình đào tạo',null,'movetrainingprocess'],
            ['movetrainingprocess-delete','Xóa Chuyển quá trình đào tạo',null,'movetrainingprocess'],

            ['subjectregister','Chuyên đề đã đăng ký','el_subject_register',null],
            ['subjectregister-watch','Xem Chuyên đề đã đăng ký',null,'subjectregister'],

            ['note','Xem Ghi chú','el_note',null],
            ['note-watch','Xem Ghi chú',null,'note'],

            ['course-plan','Kế hoạch đào tạo','el_course_plan',null],
            ['course-plan-create','Thêm mới Kế hoạch đào tạo',null,'course-plan'],
            ['course-plan-edit','Sửa Kế hoạch đào tạo',null,'course-plan'],
            ['course-plan-approved','Duyệt/Từ chối Kế hoạch đào tạo',null,'course-plan'],
            ['course-plan-delete','Xóa Kế hoạch đào tạo',null,'course-plan'],
            ['course-plan-create-object','Thêm đối tượng Kế hoạch đào tạo',null,'course-plan'],
            ['course-plan-delete-object','Xóa đối tượng Kế hoạch đào tạo',null,'course-plan'],
            ['course-plan-create-cost','Thêm chi phí Kế hoạch đào tạo',null,'course-plan'],
            ['course-plan-create-schedule','Thêm Lịch học Kế hoạch đào tạo',null,'course-plan'],
            ['course-plan-delete-schedule','Xóa chi phí Kế hoạch đào tạo',null,'course-plan'],
            ['course-plan-create-condition','Thêm điều kiện Kế hoạch đào tạo',null,'course-plan'],
            ['course-plan-add-teacher','Thêm giảng viên Kế hoạch đào tạo',null,'course-plan'],
            ['course-plan-delete-teacher','Xóa giảng viên Kế hoạch đào tạo',null,'course-plan'],

            ['topic','Xử lý tình huống','el_topic',null],
            ['topic-create','Thêm mới Xử lý tình huống',null,'topic'],
            ['topic-edit','Sửa Xử lý tình huống',null,'topic'],
            ['topic-delete','Xóa Xử lý tình huống',null,'topic'],
            ['topic-isopen','Bật/tắt Xử lý tình huống',null,'topic'],

            ['situation','Thảo luận Tình huống','el_situation',null],
            ['situation-create','Thêm mới Thảo luận Tình huống',null,'situation'],
            ['situation-edit','Sửa Thảo luận Tình huống',null,'situation'],
            ['situation-delete','Xóa Thảo luận Tình huống',null,'situation'],

            ['user-take-leave','Nhân viên nghỉ phép','el_profile_take_leave',null],
            ['user-take-leave-create','Thêm mới Nhân viên nghỉ phép',null,'user-take-leave'],
            ['user-take-leave-edit','Sửa Nhân viên nghỉ phép',null,'user-take-leave'],
            ['user-take-leave-delete','Xóa Nhân viên nghỉ phép',null,'user-take-leave'],

            ['training-by-title','Lộ trình đào tạo','el_training_by_title',null],
            ['training-by-title-create','Thêm mới chức danh',null,'training-by-title'],
            ['training-by-title-delete','Xóa chức danh',null,'training-by-title'],
            ['training-by-title-detail-create','Thêm chuyên đề theo chức danh',null,'training-by-title'],
            ['training-by-title-detail-edit','Sửa chuyên đề theo chức danh',null,'training-by-title'],
            ['training-by-title-detail-delete','Xóa chuyên đề theo chức danh',null,'training-by-title'],
            ['training-by-title-result','Kết quả lộ trình đào tạo',null,'training-by-title'],

            ['approved-process','Phân quyền phê duyệt','el_approved_process',null],
            ['approved-process-create','Thêm mới',null,'approved-process'],
            ['approved-process-edit','Sửa',null,'approved-process'],
            ['approved-process-delete','Xóa',null,'approved-process'],

            ['warehouse','Quản lý media file','el_warehouse',null],
            ['warehouse-create','Thêm mới',null,'warehouse'],
            ['warehouse-edit','Sửa',null,'warehouse'],
            ['warehouse-delete','Xóa',null,'warehouse'],

            ['warehouse-folder','Quản lý media file (folder)','el_warehouse_folder',null,'el_warehouse'], // extend từ el_warehouse

            ['log-view-course','Lịch sử truy cập khóa học','el_log_view_course',null],
            ['model-history','Lịch sử cập nhật','el_model_history',null],

            ['api-manual','Quản lý API (IHRP)','el_api',null],
            ['api-manual-sync','Cập nhật',null,'el_api'],

            ['api-manual','Quản lý API (IHRP)','el_api',null],
            ['api-manual-sync','Cập nhật',null,'el_api'],

            ['unit-manager-setting','Setup trưởng đơn vị tự động','el_unit_manager_setting',null],
            ['unit-manager-setting-create','Thêm mới',null,'unit-manager-setting'],
            ['unit-manager-setting-edit','Sửa',null,'unit-manager-setting'],
            ['unit-manager-setting-delete','Xóa',null,'unit-manager-setting'],
            ['unit-manager-setting-import','Import',null,'unit-manager-setting'],

            ['course-old','Khóa học cũ','el_course_old',null],
        ];

        //DB::table('el_permissions')->delete();
        foreach ($permissions as $key => $value) {
            $extend = isset($value[4])?$value[4]:null;
            Permission::query()->updateOrCreate(
                [
                'name' => $value[0],
                ],
                [
                    'description' => $value[1],
                    'model' => $value[2],
                    'parent' => $value[3],
                    'extend' => $extend,
                ]);
        }
    }
}
